"""add_webhook_subscriptions

Revision ID: 6d574a660cd9
Revises: ca0b444bf2f5
Create Date: 2026-02-14 23:33:03.449127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d574a660cd9'
down_revision: Union[str, None] = 'ca0b444bf2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notification_attempts', sa.Column('webhook_subscription_id', sa.UUID(), nullable=True))
    op.add_column('notification_attempts', sa.Column('payload', sa.Text(), nullable=True))
    op.alter_column('notification_attempts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'notification_attempts', 'webhook_subscriptions', ['webhook_subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_attempts', type_='foreignkey')
    op.alter_column('notification_attempts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notification_attempts', 'payload')
    op.drop_column('notification_attempts', 'webhook_subscription_id')
    op.drop_table('webhook_subscriptions')
    # ### end Alembic commands ###
